code --install-extension PKief.material-icon-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension usernamehw.errorlens
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension svelte.svelte-vscode
code --install-extension wix.vscode-import-cost
code --install-extension rangav.vscode-thunder-client
code --install-extension ritwickdey.LiveServer
code --install-extension MS-vsliveshare.vsliveshare
code --install-extension devine-davies.make-hidden
code --install-extension Prisma.prisma